[platformio]
src_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
  bblanchon/ArduinoJson@^7.0.0
