[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<ESP32_WAZE_HUD.ino>
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
  bblanchon/ArduinoJson@^7.0.0
