[platformio]
src_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -I src

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
  bblanchon/ArduinoJson@^7.0.0
  lvgl/lvgl@8.3.11
