#!/usr/bin/env python3
"""Generate LVGL 8.3 (lv_font_fmt_txt, 4 bpp, uncompressed) C fonts from a TTF.
Pure Pillow/FreeType: no lv_font_conv / node needed.
usage: gen_lv_font.py <ttf> <size> <name> <out.c-fragment> <range spec...>
range spec: 20-7E  C0-FF  1EA0-1EF9  102,103,110  (hex, comma separated)
"""
import sys, math
from PIL import Image, ImageDraw, ImageFont

def parse_ranges(specs):
    cps = set()
    for spec in specs:
        for part in spec.split(','):
            part = part.strip()
            if not part: continue
            if '-' in part:
                a, b = part.split('-'); cps.update(range(int(a,16), int(b,16)+1))
            else:
                cps.add(int(part,16))
    return sorted(cps)

def build(ttf, size, name, cps):
    font = ImageFont.truetype(ttf, size)
    asc, desc = font.getmetrics()
    glyphs = []  # (cp, bitmap_bytes, adv16, w, h, ofs_x, ofs_y)
    for cp in cps:
        ch = chr(cp)
        adv = font.getlength(ch)
        l, t, r, b = font.getbbox(ch, anchor='ls')
        w, h = r - l, b - t
        data = b''
        if w > 0 and h > 0:
            img = Image.new('L', (w, h), 0)
            ImageDraw.Draw(img).text((-l, -t), ch, font=font, fill=255, anchor='ls')
            px = [min(15, (v + 8) // 17) for v in img.tobytes()]
            if len(px) % 2: px.append(0)
            data = bytes((px[i] << 4) | px[i+1] for i in range(0, len(px), 2))
        else:
            w = h = 0; l = 0; b = 0
        glyphs.append((cp, data, int(round(adv * 16)), w, h, l, -b))
    return asc, desc, glyphs

def group_ranges(cps):
    """Split into contiguous runs (>=8 long -> tiny format0) and sparse leftovers."""
    runs, cur = [], [cps[0]]
    for c in cps[1:]:
        if c == cur[-1] + 1: cur.append(c)
        else: runs.append(cur); cur = [c]
    runs.append(cur)
    return runs

def emit(name, ttf, size, cps):
    asc, desc, glyphs = build(ttf, size, name, cps)
    idx = {g[0]: i + 1 for i, g in enumerate(glyphs)}  # glyph id 0 reserved
    out = []
    A = out.append
    guard = name.upper()
    A('/* Generated by tools/gen_lv_font.py from %s, %dpx, 4bpp. Do not edit by hand. */' % (ttf.split('/')[-1], size))
    A('#ifdef __has_include\n    #if __has_include("lvgl.h")\n        #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n            #define LV_LVGL_H_INCLUDE_SIMPLE\n        #endif\n    #endif\n#endif\n#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n    #include "lvgl.h"\n#else\n    #include "lvgl/lvgl.h"\n#endif\n')
    A('#ifndef %s\n#define %s 1\n#endif\n#if %s\n' % (guard, guard, guard))
    A('#ifndef LV_ATTRIBUTE_LARGE_CONST\n#define LV_ATTRIBUTE_LARGE_CONST\n#endif\n')
    # bitmap
    A('static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {')
    offs = []; pos = 0; lines = []
    for g in glyphs:
        offs.append(pos); pos += len(g[1])
        if g[1]:
            lines.append('    /* U+%04X */ ' % g[0] + ', '.join('0x%02x' % x for x in g[1]) + ',')
    if not lines: lines.append('    0x00,')
    A('\n'.join(lines)); A('};\n')
    assert pos < (1 << 20)
    A('static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {')
    A('    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,')
    for g, o in zip(glyphs, offs):
        assert g[2] < 4096 and g[3] < 256 and g[4] < 256 and -128 <= g[5] < 128 and -128 <= g[6] < 128
        A('    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d}, /* U+%04X */' % (o, g[2], g[3], g[4], g[5], g[6], g[0]))
    A('};\n')
    # cmaps
    cm = []; sparse_lists = []
    runs = group_ranges(cps)
    sparse_pool = []
    for r in runs:
        if len(r) >= 8:
            cm.append(('tiny', r[0], len(r), idx[r[0]], None))
        else:
            sparse_pool.extend(r)
    # sparse pool -> chunks that keep offsets < 65536 (always true here)
    if sparse_pool:
        sparse_pool.sort()
        # glyph ids in a sparse cmap are consecutive, so only group while ids are consecutive
        chunk = [sparse_pool[0]]
        chunks = []
        for c in sparse_pool[1:]:
            if idx[c] == idx[chunk[-1]] + 1: chunk.append(c)
            else: chunks.append(chunk); chunk = [c]
        chunks.append(chunk)
        for ch in chunks:
            cm.append(('sparse', ch[0], ch[-1] - ch[0] + 1, idx[ch[0]], ch))
    cm.sort(key=lambda x: x[1])
    n = 0
    for c in cm:
        if c[0] == 'sparse':
            A('static const uint16_t unicode_list_%d[] = {%s};' % (n, ', '.join('0x%x' % (u - c[1]) for u in c[4])))
            n += 1
    A('\nstatic const lv_font_fmt_txt_cmap_t cmaps[] = {')
    n = 0
    for c in cm:
        if c[0] == 'tiny':
            A('    {.range_start = %d, .range_length = %d, .glyph_id_start = %d, .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},' % (c[1], c[2], c[3]))
        else:
            A('    {.range_start = %d, .range_length = %d, .glyph_id_start = %d, .unicode_list = unicode_list_%d, .glyph_id_ofs_list = NULL, .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},' % (c[1], c[2], c[3], n, len(c[4])))
            n += 1
    A('};\n')
    A('#if LVGL_VERSION_MAJOR == 8\nstatic lv_font_fmt_txt_glyph_cache_t cache;\n#endif\n')
    A('static const lv_font_fmt_txt_dsc_t font_dsc = {\n    .glyph_bitmap = glyph_bitmap,\n    .glyph_dsc = glyph_dsc,\n    .cmaps = cmaps,\n    .kern_dsc = NULL,\n    .kern_scale = 0,\n    .cmap_num = %d,\n    .bpp = 4,\n    .kern_classes = 0,\n    .bitmap_format = 0,\n#if LVGL_VERSION_MAJOR == 8\n    .cache = &cache\n#endif\n};\n' % len(cm))
    A('const lv_font_t %s = {\n    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n    .line_height = %d,\n    .base_line = %d,\n    .subpx = LV_FONT_SUBPX_NONE,\n    .underline_position = -2,\n    .underline_thickness = 1,\n    .dsc = &font_dsc\n};\n' % (name, asc + desc, desc))
    A('#endif /*#if %s*/' % guard)
    return '\n'.join(out), glyphs, asc, desc, pos

if __name__ == '__main__':
    ttf, size, name, outp = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    cps = parse_ranges(sys.argv[5:])
    src, glyphs, asc, desc, nbytes = emit(name, ttf, size, cps)
    open(outp, 'w').write(src)
    print(name, size, 'glyphs', len(glyphs), 'bitmap bytes', nbytes, 'line', asc + desc)
